"use client";

import { useRouter } from "next/navigation";
import dynamic from "next/dynamic";

const LawyerCanvas = dynamic(() => import("../../components/Robot"), { ssr: false });

export default function KonsultasiBasePage() {
  const router = useRouter();

  // Fungsi sakti untuk membuat ID obrolan unik dan langsung melempar ke halaman slug [id]
  const handleStartConsultation = () => {
    const autoGeneratedId = `session-${Date.now()}`;
    router.push(`/konsultasi/${autoGeneratedId}`);
  };

  return (
    <div className="min-h-[calc(100vh-80px)] w-full bg-[#0B0C10] overflow-x-hidden font-sans flex items-center selection:bg-amber-500 selection:text-zinc-950">
      
      {/* AREA HERO COCOK DENGAN KONSISTENSI BERANDA */}
      <main className="max-w-7xl mx-auto px-6 py-12 md:py-20 w-full grid grid-cols-1 lg:grid-cols-12 gap-12 items-center relative z-10">
        
        {/* Sisi Teks Kiri */}
        <div className="lg:col-span-7 space-y-5 md:space-y-6 text-left">
          <div className="inline-flex items-center gap-2 bg-black/80 border border-amber-500/30 px-4 py-2 rounded-full text-[10px] sm:text-xs text-amber-500 uppercase tracking-widest font-bold">
            <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span>
            Sistem Hukum Berbasis AI
          </div>
          
          <h1 className="font-serif text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight leading-[1.1] text-white">
            Masa Depan Praktik <br />
            <span className="text-amber-500 block mt-1 lg:mt-2">Hukum Terintegrasi</span>
          </h1>
          
          <p className="text-zinc-300 text-sm md:text-base lg:text-lg max-w-xl font-light leading-relaxed">
            Transformasi digital litigasi modern Indonesia. Akselerasi riset yurisprudensi dan draf berkas perkara akurat dalam satu genggaman.
          </p>
          
          <div className="flex pt-2 md:pt-4">
            {/* PERBAIKAN: Tombol diubah menjadi Konsultasi AI Sekarang */}
            <button 
              onClick={handleStartConsultation} 
              className="w-full sm:w-auto text-center bg-amber-500 text-black font-bold px-10 py-4 rounded-xl hover:bg-amber-400 hover:scale-105 transition-all text-sm sm:text-base shadow-lg shadow-amber-500/20 uppercase tracking-wider"
            >
              Konsultasi AI Sekarang
            </button>
          </div>
        </div>

        {/* Sisi Robot Kanan dengan Aura Glow Emas Menyala */}
        <div className="lg:col-span-5 h-[380px] sm:h-[450px] w-full relative flex items-center justify-center overflow-visible">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[260px] sm:w-[320px] h-[260px] sm:h-[320px] bg-gradient-to-tr from-amber-500/20 to-yellow-600/10 rounded-full blur-[70px] sm:blur-[100px] animate-pulse pointer-events-none z-0" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[100px] h-[100px] bg-amber-400/10 rounded-full blur-[30px] pointer-events-none z-0" />
          
          <div className="w-full h-full relative z-10">
            <LawyerCanvas />
          </div>
        </div>

      </main>
    </div>
  );
}